services:
  # Ollama service running GPT-OSS
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # API Gateway with ngrok
  gpt-oss-gateway:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - OLLAMA_BASE_URL=http://ollama:11434
      - GPT_OSS_MODEL=${GPT_OSS_MODEL:-gpt-oss:20b}
    restart: unless-stopped

  # Optional: Web UI for testing
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
  open_webui_data: